### ISSUE TITLE
Spring cloud commons 2.0.0M9 compatible?

### ISSUE THREAD

**Issue by dzonekl** [spring-cloud-incubator/spring-cloud-kubernetes#211]
I get an exception [2] when adding @EnableDiscoveryClient, this class is not part of: commons 2.0.0M9 release. Any way to get spring cloud k8s work with the latest spring cloud version? 
Thank You Christophe

[1] Dependencies

We use gradle and spring dependency management, with Maven BOM import. 

Versions: 
springCloudK8s = '0.2.0.RELEASE'
springCloudVersion = 'Finchley.M9'

Dependencies:

'org.springframework.cloud:spring-cloud-starter',
"org.springframework.cloud:spring-cloud-starter-kubernetes:${springCloudK8s}"

dependencyManagement {
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:$springCloudVersion"
            mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
        }
    }

With this setup, the classpath is: 

Gradle: org.springframework.cloud:spring-cloud-starter-kubernetes:0.2.0.RELEASE
Gradle: org.springframework.cloud:spring-cloud-starter:2.0.0.M9
Gradle: org.springframework.cloud:spring-cloud-commons:2.0.0.M9
Gradle: org.springframework.cloud:spring-cloud-kubernetes-core:0.2.0.RELEASE
Gradle: org.springframework.cloud:spring-cloud-kubernetes-discovery:0.2.0.RELEASE

[2] NCDFE
`Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/client/discovery/AbstractDiscoveryLifecycle
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:641)
	... 20 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.client.discovery.AbstractDiscoveryLifecycle
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 common frames omitted
`

**Comment by dzonekl** [comment]
Hi there, 
I upped some of the dependencies: 

Gradle: org.springframework.cloud:spring-cloud-commons:2.0.0.RELEASE
Gradle: org.springframework.cloud:spring-cloud-kubernetes-core:0.3.0.BUILD-SNAPSHOT
Gradle: org.springframework.cloud:spring-cloud-kubernetes-discovery:0.3.0.BUILD-SNAPSHOT
Gradle: org.springframework.cloud:spring-cloud-starter-kubernetes:0.3.0.BUILD-SNAPSHOT

Exceptions is gone, guess the 0.3.0 version will target Finchley Cloud release? 
Haven't tested on k8s yet, will report back here as well (if of any value).
