### ISSUE TITLE
NoClassDefFound org/springframework/boot/yaml/SpringProfileDocumentMatcher when using a yaml ConfigMap

### ISSUE THREAD

**Issue by psoares** [spring-cloud-incubator/spring-cloud-kubernetes#217]
I tried a simple gradle project to test the ConfigMap property resolution mechanism.
When using the following ConfigMap configuration file, everything works fine:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubetest
data:
  hello.message: Hello from kubernetes
```

However, when using the yaml syntax below, it fails:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubetest
data:
  application.yaml: |-
   hello:
     message: Hello from kubernetes
```

The exception I get is:
```
java.lang.NoClassDefFoundError: org/springframework/boot/yaml/SpringProfileDocumentMatcher
	at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.lambda$yamlParserGenerator$0(ConfigMapPropertySource.java:108) ~[spring-cloud-kubernetes-config-0.2.0.RELEASE.jar!/:0.2.0.RELEASE]
	at java.util.function.Function.lambda$andThen$1(Function.java:88) ~[na:1.8.0_171]
	at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.getData(ConfigMapPropertySource.java:82) ~[spring-cloud-kubernetes-config-0.2.0.RELEASE.jar!/:0.2.0.RELEASE]
	at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.<init>(ConfigMapPropertySource.java:57) ~[spring-cloud-kubernetes-config-0.2.0.RELEASE.jar!/:0.2.0.RELEASE]
	at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.locate(ConfigMapPropertySourceLocator.java:44) ~[spring-cloud-kubernetes-config-0.2.0.RELEASE.jar!/:0.2.0.RELEASE]
	at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.locate(ConfigMapPropertySourceLocator.java:28) ~[spring-cloud-kubernetes-config-0.2.0.RELEASE.jar!/:0.2.0.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94) ~[spring-cloud-context-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:633) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at com.mg.reference.entrez.gene.repositories.KubetestApplication.main(KubetestApplication.java:14) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app.jar:na]
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.yaml.SpringProfileDocumentMatcher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[app.jar:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
	... 21 common frames omitted
```

My gradle.build file looks like this:

```
buildscript {
	ext {
		springBootVersion = '2.0.3.RELEASE'
	}
	repositories {
		maven { url "http://repo.spring.io/plugins-release" }
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

plugins {
    id 'com.palantir.docker' version '0.19.2'
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.demo'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
}

ext {
	springCloudVersion = 'Finchley.RELEASE'
}

dependencies {
	compile('org.springframework.boot:spring-boot-starter')
	compile('org.springframework.boot:spring-boot-starter-webflux')
	compile('org.springframework.boot:spring-boot-starter-actuator')
	compile('org.springframework.cloud:spring-cloud-starter-kubernetes:0.2.0.RELEASE')
	compile('org.springframework.cloud:spring-cloud-starter-kubernetes-config:0.2.0.RELEASE')
	compile('org.springframework.cloud:spring-cloud-starter-config')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

docker {
	copySpec.from("./build/libs").into("./build/libs")
	name "demo/${project.archivesBaseName}:${project.version}"
	tags "latest"
	files tasks.jar.outputs
}

build.dependsOn tasks.dockerClean
build.finalizedBy tasks.docker
```

My src/main/resources/bootstrap.properties file looks like this:
```
spring.application.name=kubetest
spring.cloud.kubernetes.discovery.enabled=false
```

My app main class looks like this:
```
package com.mg.reference.entrez.gene.repositories;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.reactive.config.EnableWebFlux;

@SpringBootApplication
@EnableWebFlux
public class KubetestApplication {

	public static void main(String[] args) {
		SpringApplication.run(KubetestApplication.class, args);
	}
	
	@Bean
	public String hello(@Value("${hello.message}") String message) {
		System.out.println("MESSAGE: " + message);
		return message;
	}
	
}
```

**Comment by spencergibb** [comment]
Version 0.2.0 does not work with boot 2.x only 1.5.x. Version 0.3.0.RC1 works with the 2.x line. A RELEASE will be forthcoming within a month
