### ISSUE TITLE
goal io.fabric8:fabric8-maven-plugin:3.2.26:resource failed: Type io.fabric8.kubernetes.api.model.extensions.StatefulSetBuilder not present

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud-incubator/spring-cloud-kubernetes#41]
It looks like that spring cloud kubernetes is not align anymore with f-m-p

```
mvn dependency:tree | grep kubernetes
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[INFO] |  +- io.fabric8:spring-cloud-starter-kubernetes-all:jar:0.1.4:compile
[INFO] |  |  +- io.fabric8:spring-cloud-kubernetes-core:jar:0.1.4:compile
[INFO] |  |  +- io.fabric8:spring-cloud-kubernetes-discovery:jar:0.1.4:compile
[INFO] |  |  +- io.fabric8:spring-cloud-kubernetes-archaius:jar:0.1.4:compile
[INFO] |  |  +- io.fabric8:spring-cloud-kubernetes-ribbon:jar:0.1.4:compile
[INFO] |  |  +- io.fabric8:spring-cloud-kubernetes-hystrix:jar:0.1.4:compile
[INFO] |  |  +- io.fabric8:spring-cloud-kubernetes-zipkin:jar:0.1.4:compile
[INFO] |  +- io.fabric8:spring-cloud-kubernetes-compat:jar:0.1.4:compile
[INFO] |  \- io.fabric8:kubernetes-client:jar:1.4.19:compile
[INFO] |     +- io.fabric8:kubernetes-model:jar:1.0.63:compile
```

So this error is reported during mvn fabric8:resource goal

```
Caused by: java.lang.TypeNotPresentException: Type io.fabric8.kubernetes.api.model.extensions.StatefulSetBuilder not present
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:90)
        at java.lang.Class.getGenericSuperclass(Class.java:777)
        at io.fabric8.kubernetes.api.builder.TypedVisitor.getTypeArguments(TypedVisitor.java:47)
        at io.fabric8.kubernetes.api.builder.TypedVisitor.getType(TypedVisitor.java:19)
        at io.fabric8.kubernetes.api.builder.BaseFluent.canVisit(BaseFluent.java:51)
        at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:93)
        at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:85)
        at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
        at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:91)
        at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:85)
        at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
        at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:91)
        at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:85)
        at io.fabric8.maven.enricher.standard.ImageEnricher.ensureTemplateSpecsInStatefulSet(ImageEnricher.java:168)
        at io.fabric8.maven.enricher.standard.ImageEnricher.ensureTemplateSpecs(ImageEnricher.java:110)
        at io.fabric8.maven.enricher.standard.ImageEnricher.addMissingResources(ImageEnricher.java:97)
        at io.fabric8.maven.plugin.enricher.EnricherManager$1.apply(EnricherManager.java:112)
        at io.fabric8.maven.plugin.enricher.EnricherManager$1.apply(EnricherManager.java:109)
        at io.fabric8.maven.plugin.enricher.EnricherManager.loop(EnricherManager.java:212)
        at io.fabric8.maven.plugin.enricher.EnricherManager.createDefaultResources(EnricherManager.java:109)
        at io.fabric8.maven.plugin.enricher.EnricherManager.createDefaultResources(EnricherManager.java:104)
        at io.fabric8.maven.plugin.mojo.build.ResourceMojo.generateAppResources(ResourceMojo.java:407)
        at io.fabric8.maven.plugin.mojo.build.ResourceMojo.generateResources(ResourceMojo.java:347)
        at io.fabric8.maven.plugin.mojo.build.ResourceMojo.executeInternal(ResourceMojo.java:197)
        at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:74)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more

```

**Comment by cmoulliard** [comment]
From James

```
looks like its not been updated in a while https://github.com/fabric8io/spring-cloud-kubernetes

do a PR for this https://github.com/fabric8io/spring-cloud-kubernetes/blob/master/pom.xml#L80 to use the same version as fmp and we can try cut a release soon

or try use an older fmp that uses the same kube client version (but figuring that out might be harder)
really spring cloud k8s should have a PR against it whenever we update the kube model/client like the rest of fabric8

here's where to do it if you wanna submit a PR https://github.com/fabric8io/kubernetes-client/blob/master/release.groovy#L69
```

**Comment by spencergibb** [comment]
What's  `f-m-p`?

**Comment by iocanel** [comment]
f-m-p is an abbreviation for [fabric8-maven-plugin](https://github.com/fabric8io/fabric8-maven-plugin).

So, in other words this means that spring-cloud-kubernetes and f-m-p r using incompatible kubernetes-client version.

I intend to upgrade once we get kubernets-client 2.3.

**Comment by cmoulliard** [comment]
@iocanel As the Fabric8 maven plugin is only used within the `spring-cloud-kubernetes-examples` project, can we avoid this issue by defining for the project and the plugin the same Kubernetes Api client ?

**Comment by iocanel** [comment]
The issue is not related with what version of fmp we use here, but what version of kubernetes-client.

**Comment by iocanel** [comment]
at least this is my understanding.
