### ISSUE TITLE
No qualifying bean of type 'com.netflix.client.config.IClientConfig' available

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud-incubator/spring-cloud-kubernetes#81]
I'm developing a new Java test case for the Ribbon module. The code is similar to what has been done within the groovy test case at the exception that If I run it using the [java junit testclass](https://github.com/cmoulliard/spring-cloud-kubernetes/blob/c6e8b8d30250b36719a6104f144320500680cd55/spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/RibbonTest.java), this bean exception error is reported as no IClientConfig object impl the interface has been found

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ribbonServerList' defined in class path resource [org/springframework/cloud/kubernetes/ribbon/KubernetesRibbonClientConfiguration.class]: Unsatisfied dependency expressed through method 'ribbonServerList' parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.client.config.IClientConfig' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.client.config.IClientConfig' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

If I include a DefaultClientImpl as [such](https://github.com/cmoulliard/spring-cloud-kubernetes/blob/745b11b8bca667cd745196d50632d745542749b6/spring-cloud-kubernetes-ribbon/src/test/java/org/springframework/cloud/kubernetes/ribbon/TestApplication.java#L30-L36), the error is gone

Question:
- Why Groovy Test class doesn't has this error while this is the case for the java Test junit class ?
- Do we have to specify a DefaultClientConfigImpl or can this client been instantiated out of box ?

Another error that I experiment is that when the method defined for the @Test will be called then the okhttp3 client of the Ribbon Kubernetes Client will try to use the kubernetes default server instead of the mock server address. 

Is there a workaround ?

```
2017-05-15 18:51:26.165  INFO 26020 --- [WebServer 60046] okhttp3.mockwebserver.MockWebServer      : MockWebServer[60046] starting to accept connections
2017-05-15 18:51:26.185  INFO 26020 --- [WebServer 60047] okhttp3.mockwebserver.MockWebServer      : MockWebServer[60047] starting to accept connections
2017-05-15 18:51:26.387  INFO 26020 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@994544: startup date [Mon May 15 18:51:26 CEST 2017]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@149f5761
2017-05-15 18:51:26.410  INFO 26020 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-05-15 18:51:26.499  INFO 26020 --- [           main] c.netflix.config.ChainedDynamicProperty  : Flipping property: testapp.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2017-05-15 18:51:26.523  INFO 26020 --- [           main] c.n.u.concurrent.ShutdownEnabledTimer    : Shutdown hook installed for: NFLoadBalancer-PingTimer-testapp
2017-05-15 18:51:26.552  INFO 26020 --- [           main] c.netflix.loadbalancer.BaseLoadBalancer  : Client:testapp instantiated a LoadBalancer:DynamicServerListLoadBalancer:{NFLoadBalancer:name=testapp,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
2017-05-15 18:51:26.556  INFO 26020 --- [           main] c.n.l.DynamicServerListLoadBalancer      : Using serverListUpdater PollingServerListUpdater
2017-05-15 18:51:26.598  WARN 26020 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ribbonLoadBalancingHttpClient' defined in org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$HttpClientRibbonConfiguration: Unsatisfied dependency expressed through method 'ribbonLoadBalancingHttpClient' parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ribbonLoadBalancer' defined in org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.loadbalancer.ILoadBalancer]: Factory method 'ribbonLoadBalancer' threw exception; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
2017-05-15 18:51:26.612  INFO 26020 --- [WebServer 60029] okhttp3.mockwebserver.MockWebServer      : MockWebServer[60029] done accepting connections: Socket closed
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.725 sec <<< FAILURE! - in org.springframework.cloud.kubernetes.ribbon.RibbonTest
testGreetingEndpoint(org.springframework.cloud.kubernetes.ribbon.RibbonTest)  Time elapsed: 0.491 sec  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ribbonLoadBalancingHttpClient' defined in org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$HttpClientRibbonConfiguration: Unsatisfied dependency expressed through method 'ribbonLoadBalancingHttpClient' parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ribbonLoadBalancer' defined in org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.loadbalancer.ILoadBalancer]: Factory method 'ribbonLoadBalancer' threw exception; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at org.springframework.cloud.kubernetes.ribbon.RibbonTest.testGreetingEndpoint(RibbonTest.java:109)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ribbonLoadBalancer' defined in org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.loadbalancer.ILoadBalancer]: Factory method 'ribbonLoadBalancer' threw exception; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at org.springframework.cloud.kubernetes.ribbon.RibbonTest.testGreetingEndpoint(RibbonTest.java:109)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.loadbalancer.ILoadBalancer]: Factory method 'ribbonLoadBalancer' threw exception; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at org.springframework.cloud.kubernetes.ribbon.RibbonTest.testGreetingEndpoint(RibbonTest.java:109)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at org.springframework.cloud.kubernetes.ribbon.RibbonTest.testGreetingEndpoint(RibbonTest.java:109)
Caused by: java.net.UnknownHostException: kubernetes.default.svc: nodename nor servname provided, or not known
        at org.springframework.cloud.kubernetes.ribbon.RibbonTest.testGreetingEndpoint(RibbonTest.java:109)
```

**Comment by spencergibb** [comment]
If `KubernetesRibbonClientConfiguration` is created by normal spring configuration you'll get an error like that. If it's loaded as part of ribbon configuration, a `ClientConfig` instance will be auto created.

**Comment by cmoulliard** [comment]
> loaded as part of ribbon configuration

When it is define using this annotation ("@RibbonClient(name = "testapp", configuration = KubernetesRibbonClientConfiguration.class)"), will the client config be created automatically ?

**Comment by cmoulliard** [comment]
> Is there a workaround ?

I have been able to resolve the okhttp3 client (= was using the config of kube server instead of the mock server) after changing the annotation from @Before to @BeforeClass

**Comment by cmoulliard** [comment]
> it should be created

As in my case, it is not created by default, I will continue to instantiate the bean till we will figure out how to resolve that. Make sense ?

**Comment by spencergibb** [comment]
My guess is that it's getting picked up outside of `@RibbonClient`.

**Comment by cmoulliard** [comment]
Problem resolved with PR - #83 and commit 6696b361c192f38569d667572dfccaf048fbdee0

**Comment by PrachipriyaPrasad** [comment]
I'm also not able to auto wire  I'm getting **NoSuchBeanDefinitionException Exception**.

**org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.client.config.IClientConfig' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations:** 
**i tried using** 
**@SpringBootApplication(scanBasePackages={"com.netflix.client.config.IClientConfig"})**
but this is also not working for me  please help me !!

**Comment by tarunsingh2789** [comment]
@Prachi Prasad I a also facing same issue . Did you find any workaround to resolve it
